user: elk
group: elk
app_logs: <path of where your app logs are at>

filebeat_home: "/home/{{user}}/filebeat"
filebeat_image: my-own-filebeat:latest

logstash_url: <target ip of your logstash instance>
elasticsearch_url: <target ip of your elasticsearch instance>
