user: elk
group: elk

env: '{{inventory_hostname}}'

elk_home: '/home/{{user}}/elk'

# ref: https://github.com/geerlingguy/ansible-role-elasticsearch-curator
elasticsearch_curator_cron_jobs:
  - {
    name: "Run curator to close and delete old elasticsearch indices.",
    job: "/bin/curator --config {{elk_home}}/elasticsearch/curator_config.yml {{elk_home}}/elasticsearch/curator_action.yml",
    minute: "0",
    hour: "1"
  }

es_image: my-own-es:latest
ls_image: my-own-ls:latest
kb_image: my-own-kb:latest
