- name: Start docker service
  service:
    name: docker
    state: started
    enabled: yes
  register: docker_service_output
  become: yes
  ignore_errors: yes

- name: Ensure that docker has started...
  shell: docker ps
  register: docker_status
  until: docker_status.rc == 0
  failed_when: docker_status.rc == 1
  retries: 4
  delay: 5
  tags:
    - check-docker-service

- debug:
    var: docker_status
  tags:
    - check-docker-service