
- name: Configure and deploy Filebeat on APP servers
  hosts: elk-clients
  environment:
    USER: "{{user}}"
    GROUP: "{{group}}"
    FILEBEAT_HOME: "{{filebeat_home}}"
    APP_LOGS: "{{app_logs}}"
    ENV: "{{env}}"
    LOGSTASH_URL: "{{logstash_url}}"
    ELASTICSEARCH_URL: "{{elasticsearch_url}}"
    FILEBEAT_IMAGE: "{{filebeat_image}}"
    DOCKER_PW: "{{lookup('env','DOCKER_PW')}}"
    DOCKER_USER: "{{lookup('env' , 'DOCKER_USER')}}"
    DOCKER_URL: "{{lookup('env', 'DOCKER_URL')}}"

  roles:
    - filebeat
  tags:
    - deploy-fb

- name: Configure and deploy ELK
  hosts: elk
  environment:
    USER: "{{user}}"
    GROUP: "{{group}}"
    ELK_HOME: "{{elk_home}}"
    ES_IMAGE: "{{es_image}}"
    LS_IMAGE: "{{ls_image}}"
    KB_IMAGE: "{{kb_image}}"
    DOCKER_PW: "{{lookup('env','DOCKER_PW')}}"
    DOCKER_USER: "{{lookup('env' , 'DOCKER_USER')}}"
    DOCKER_URL: "{{lookup('env', 'DOCKER_URL')}}"

  roles:
    - elk
  tags:
    - deploy-elk

- name: Setup Curator for indices housekeeping
  hosts: elk
  become: yes
  roles:
    - geerlingguy.elasticsearch-curator
  tags:
    - setup-curator
    - update-curator