version: '3.2'
services:

  logstash:
    image: ${LS_IMAGE}
    build:
      context: ${ELK_HOME}/logstash
      dockerfile: Dockerfile.logstash
      args:
        - USER=${USER:-elk}
        - GROUP=${GROUP:-elk}
        - USER_ID=${USER_ID:-1001}
        - GROUP_ID=${GROUP_ID:-1001}
    ports:
      - "5044:5044"
      - "5045:5045"
      - "8080:8080"
      - "9600:9600"

    volumes:
      # - "ls-data:/usr/share/logstash/data"
      - "${ELK_HOME}/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
      - "${ELK_HOME}/logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
      - "${ELK_HOME}/logstash/pipeline:/usr/share/logstash/pipeline"

    logging:
      options:
        max-size: '50M'
    environment:
      LS_JAVA_OPTS: -Xms1g -Xmx1g

    networks:
      - elk

  elasticsearch:
    image: ${ES_IMAGE}
    build:
      context: ${ELK_HOME}/elasticsearch
      dockerfile: Dockerfile.elasticsearch
      args:
        - USER
        - GROUP
        - USER_ID
        - GROUP_ID
    ports:
      - "9200:9200"

    volumes:
      - "es-data:/usr/share/elasticsearch/data"
      - "${ELK_HOME}/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

    logging:
      options:
        max-size: '50M'
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  elasticsearch2:
    image: ${ES_IMAGE}
    build:
      context: ${ELK_HOME}/elasticsearch
      dockerfile: Dockerfile.elasticsearch
      args:
        - USER
        - GROUP
        - USER_ID
        - GROUP_ID
    volumes:
      - "es-data2:/usr/share/elasticsearch/data"
      - "${ELK_HOME}/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"

    logging:
      options:
        max-size: '50M'
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  kibana:
    image: ${KB_IMAGE}
    build:
      context: ${ELK_HOME}/kibana
      dockerfile: Dockerfile.kibana
      args:
        - USER
        - GROUP
        - USER_ID
        - GROUP_ID
    ports:
      - "5601:5601"

    volumes:
      - "kb-data:/usr/share/kibana/data"
      - "${ELK_HOME}/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml"

    logging:
      options:
        max-size: '50M'
    networks:
      - elk
volumes:
  ls-data:
  es-data:
  es-data2:
  kb-data:
networks:
  elk:
    driver: bridge

