- name: copy over docker-compose files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
  - { src: ./docker-compose.yml, dest: "{{elk_home}}/" }
  tags:
    - update-elk-conf

- name: run elasticsearch, kibanaz and logstashz
  shell: cd {{ elk_home }} && \
         env > .env && \
         docker-compose up -d
  environment:
    USER_ID: "{{user_id.stdout}}"
    GROUP_ID: "{{group_id.stdout}}"

- name: ensure ports are open and elk is running
  shell: nc -z -w5 127.0.0.1 {{ item }}
  with_items:
   - "{{ ls_tcp_port }}"
   - "{{ es_http_port }}"
   - "{{ es_tcp_port }}"
   - "{{ kibana_port }}"

  register: http_check
  until: http_check.rc == 0
  failed_when: http_check.rc == 1
  retries: 4
  delay: 15
  tags:
    - http_check

- debug:
    var: http_check

- name: Prune docker system
  shell: docker system prune -f