- name: copy over docker-compose files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
  - { src: ./docker-compose.yml, dest: "{{elk_home}}/" }
  tags:
    - update-elk-conf

- name: run elasticsearch, kibanaz and logstashz
  shell: cd {{ elk_home }} && \
         env > .env && \
         docker-compose up -d
  environment:
    USER_ID: "{{user_id.stdout}}"
    GROUP_ID: "{{group_id.stdout}}"

- name: Prune docker system
  shell: docker system prune -f