- name: copy over docker-compose files
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{group}}"
    mode: u=rwx,o=rx,g=rx
  with_items:
  - { src: ./docker-compose.yml, dest: "{{elk_home}}/" }
  notify: docker-compose file update
  tags:
    - update-elk-conf

- name: Logging into docker registry
  shell: echo $DOCKER_PW | \
        docker login -u $DOCKER_USER \
        --password-stdin $DOCKER_URL
  register: login_success
  tags:
    - login-docker
- debug:
    msg: "Stdout: {{login_success.stdout}}"
  failed_when: login_success.stdout != "Login Succeeded"
  tags:
    - login-docker

- name: check that docker is running
  import_tasks: check-docker-service.yml

- name: run elasticsearch, kibanaz and logstashz
  shell: cd {{ elk_home }} && \
         docker-compose up -d
  become_user: "{{user}}"
  environment:
    USER_ID: "{{user_id.stdout}}"
    GROUP_ID: "{{group_id.stdout}}"

- name: Prune docker system
  shell: docker system prune -f

- name: Log out of docker
  shell: docker logout $DOCKER_URL
  environment:
    DOCKER_URL: "{{lookup('env', 'DOCKER_URL')}}"