- name: ensuring group "{{user}}" exists
  group:
    name: "{{group}}"
    gid: "{{group_id}}"
    state: present

- name: ensuring docker group exists
  group:
    name: docker
    state: present

# - name: ensuring user {{user}} exists and added into group
#   user:
#     uid: "{{user_id}}"
#     groups: "{{group}}, docker"
#     name: "{{user}}"
#     state: present
#     append: yes
#   become: yes


- name: ensuring user {{user}} exists and added into group
  user:
    uid: "{{user_id}}"
    group: "{{group}}"
    name: "{{user}}"
    state: present
  become: yes

- name: Get user id
  shell: id -u {{ user }}
  register: user_id
  tags:
    - get-ids

- name: Get group id
  shell: id -g {{ user }}
  register: group_id
  tags:
    - get-ids

- name: Get docker group id
  shell: 'bash -c "cut -d: -f3 < <(getent group docker)"'
  register: docker_group_id
  tags:
    - get-ids

- debug:
    msg: "user_id: {{user_id.stdout}}, group_id: {{group_id.stdout}}, docker_group_id: {{docker_group_id.stdout}}"
  tags:
    - get-ids
