# https://github.com/carlosfrancia/ansible-elk-docker/blob/master/roles/filebeat/templates/filebeat.yml.j2
###################### Filebeat Configuration #########################

# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.inputs:

- type: log
  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /usr/share/filebeat/dockerlogs/*

  multiline:
    pattern: '[DFEWI], \['
    negate: true
    match: after

#============================= Filebeat processors ============================

processors:
- add_docker_metadata: ~

#================================ General =====================================

# Optional fields that you can specify to add additional information to the
# output.
fields:
  env: ${ENV:UNSPECIFIED}

hostname: ${HOSTNAME:FILEBEAT}
name: ${HOSTNAME:FILEBEAT}

# Write Filebeat own logs only to file to avoid catching them with itself in docker log files
logging.to_files: true
logging.to_syslog: false

#----------------------------- Logstash output --------------------------------
output.logstash:
  hosts: ["${LOGSTASH_URL}"]

#============================== Xpack Monitoring ===============================
# Filebeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.

# X-pack optional module
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["${ELASTICSEARCH_URL}"]

xpack.security.enabled: false